import type { Category } from "@/generated/prisma";

/**
 * Hand-written seed search queries per category. `queryGenerator.ts` rotates
 * through these and layers cheap template-generated long-tail variants on
 * top — this list just has to be a good, varied starting point per
 * category, not exhaustive.
 */
export const SEED_QUERIES: Record<Category, string[]> = {
  road_rage: [
    "road rage",
    "brake check",
    "brake checking dashcam",
    "angry driver",
    "aggressive driver",
    "crazy driver",
    "highway road rage",
    "dashcam confrontation",
    "driver confrontation",
    "driver argument",
    "traffic argument",
    "road rage karma",
    "brake check karma",
    "instant karma driver",
    "dangerous overtaking",
    "dashcam near miss",
    "highway confrontation",
    "parking rage",
    "aggressive overtaking",
    "insane dashcam",
    "road rage compilation",
    "driver blocks car",
    "car chase road rage",
    "angry motorist",
  ],
  dashcam: [
    "dashcam catches",
    "dashcam moment",
    "dashcam footage",
    "insane dashcam save",
    "dashcam crash",
    "dashcam fail",
    "russian dashcam",
    "dashcam near miss",
    "dashcam highway",
    "dashcam intersection",
  ],
  instant_karma: [
    "instant karma",
    "karma caught on camera",
    "instant karma compilation",
    "karma driver",
    "karma police",
    "instant justice caught on camera",
    "instant karma fail",
  ],
  crazy_driving: [
    "crazy driving",
    "insane driving",
    "reckless driver",
    "worst drivers",
    "bad drivers compilation",
    "wrong way driver",
    "street racing gone wrong",
    "drift fail",
    "crazy overtake",
  ],
  near_misses: [
    "near miss caught on camera",
    "close call dashcam",
    "almost hit",
    "near collision",
    "close call compilation",
    "narrowly avoided crash",
  ],
  crashes: [
    "car crash compilation",
    "crash caught on camera",
    "highway pileup",
    "truck crash dashcam",
    "motorcycle crash caught on camera",
    "intersection crash",
  ],
  confrontations: [
    "public confrontation",
    "parking lot confrontation",
    "store confrontation caught on camera",
    "neighbor confrontation",
    "confrontation caught on camera",
    "delivery driver confrontation",
  ],
  arguments: [
    "public argument caught on camera",
    "heated argument caught on camera",
    "argument goes wrong",
    "customer argument caught on camera",
  ],
  fails: [
    "epic fail compilation",
    "fail caught on camera",
    "instant regret",
    "worst idea caught on camera",
    "try not to laugh fails",
  ],
  funny_moments: [
    "funny moment caught on camera",
    "hilarious fail",
    "funny reaction caught on camera",
    "unexpectedly funny",
  ],
  unexpected_moments: [
    "unexpected moment caught on camera",
    "didn't see that coming",
    "plot twist caught on camera",
    "shocking twist caught on camera",
  ],
  satisfying_moments: [
    "satisfying moment caught on camera",
    "oddly satisfying real life",
    "satisfying karma",
    "satisfying comeback caught on camera",
  ],
  shocking_moments: [
    "shocking moment caught on camera",
    "shocking footage",
    "you won't believe this caught on camera",
    "shocking reaction caught on camera",
  ],
  weird_moments: [
    "weird moment caught on camera",
    "bizarre footage",
    "strange encounter caught on camera",
    "weirdest thing caught on camera",
  ],
  general_viral: [
    "caught on camera",
    "viral video moment",
    "you have to see this",
    "internet's newest viral video",
    "goes viral",
  ],
};

/** Cheap template modifiers used to generate long-tail variants per category. */
export const LONG_TAIL_MODIFIERS = [
  "caught on camera",
  "gone wrong",
  "compilation",
  "2026",
  "real footage",
  "unbelievable",
  "you won't believe",
  "best of",
];
